### ISSUE TITLE
SynPDF interface to the Delphi world

### ISSUE THREAD

**Issue by rs0xFFFF** [synopse/SynPDF#60]
Hi, the interface to SynPDF is a bit weird. The canvas is not compatible with the Delphi/WinAPI canvas.

  pdf := TPdfDocument.Create;    
  page := pdf.AddPage;
  page.Canvas.Line(..)  <---  <>TCanvas
  
Why not just work with a handle? It's a clean and simple solution.

  var hdc: THandle;
  
  pdf := TPdfDocument.Create;    
  hdc := pdf.AddPage;
  canvas := TCanvas.Create;
  canvas.handle := hdc;
  canvas.Line(..)  
  
In addition, you have the advantage that you are 100% assignment-compatible with the WinAPI.

**Comment by synopse** [comment]
Please use the forum for such discussion.
https://synopse.info/forum/viewforum.php?id=1

TPdfDocument has its own canvas, because it was designed to reduce dependencies with the WinAPI.
Implementing a Windows Handle is not simple at all: this is a very low-level complex task.
You can use a handle with the TPdfGdiDocument. This is a metafile canvas, compatible with the WinAPI.
